import { createTheme } from "@shopify/restyle";

const theme = createTheme({
  colors: {
    "primary-color": "#25786E",
    "elevation-background-dark-1": "#303030",
    "elevation-background-dark-2": "#141414",
    "elevation-background-dark-3": "#292929",
    "elevation-background-dark-4": "#1F1F1F",
    "interactive-text-dark-1": "#DBDBDB",
    "interactive-border-1": "#858585",
    "interactive-primary-text-idle": "#DBDBDB",
    "interactive-primary-text-pressed": "#858585",
    "interactive-primary-text-disabled": "#666666",
    "interactive-primary-bg-idle": "#25786E",
    "interactive-primary-bg-pressed": "#125E57",
    "interactive-secondary-on-idle": "#303030",
    "interactive-secondary-on-pressed": "#292929",
    "informational-error": "#d43f2bff",
    "informational-error-outline": "#e85e4bff",
    "interactive-card-yellow": "#FFD035",
    "interactive-card-blue": "#477feaff",
    "interactive-card-green": "#16a34aff",
    "interactive-orange": "#f5880bff",
    "interactive-magenta": "#a83260",
    "interactive-purple": "#690470",
    transparent: "transparent",
    "elevation-background": "#f9fafbff",
    "background-light-gray": "#EFF0F6",
    "elevation-surface-1": "#f3f4f6ff",
    "elevation-outline-1": "#e5e7ebff",
    "elevation-outline-2": "#d1d5dbff",
    "interactive-primary-on": "#25786E",
    "interactive-primary-disabled": "#9ac2f6ff",
    "interactive-secondary-on": "#ffffffff",
    "interactive-secondary-disabled": "#9ca3afff",
    "interactive-outlined-on": "#111827ff",
    "interactive-outlined-idle": "#374151ff",
    "interactive-outlined-disabled": "#9ca3afff",
    "interactive-text-disabled": "#6b7280ff",
    "text-default-primary": "#111827ff",
    "button-text-color": "#000000",
    "text-default-secondary": "#374151ff",
    "text-inverted-primary": "#f3f4f6ff",
    "text-inverted-secondary": "#e5e7ebff",
    "informational-success": "#16a34aff",
    "informational-success-outline": "#4ade81ff",
    "informational-warning": "#f5880bff",
    "informational-warning-outline": "#fb9724ff",
    "interactive-text-on-bg-2": "#2b51d4ff",
    "interactive-text-on-bg": "#1f2937ff",
    "text-default-tertiary": "#6b7280ff",
    "text-inverted-tertiary": "#d1d5dbff",
    "text-disabled": "#b1b1b1",
    "interactive-outlined-pressed": "#477feaff",
    "interactive-text-pressed": "#477feaff",
    "interactive-outlined-on-toggled": "#ffffffff",
    "interactive-outlined-toggled": "#111827ff",
    "interactive-icon-idle": "#374151ff",
    "interactive-icon-idle-2": "#058747",
    "interactive-icon-pressed": "#04954F",
    "interactive-icon-disabled": "#6b7280ff",
    "interactive-icon-inactive": "#E5E3EC",
    "interactive-icon-on": "#ffffffff",
    "elevation-surface-2": "#e5e7ebff",
    "interactive-tertiary-on": "#4b5563ff",
    "interactive-tertiary-idle": "#e5e7ebff",
    "interactive-tertiary-pressed": "#9ca3afff",
    "interactive-tertiary-on-disabled": "#9ca3afff",
    "interactive-tertiary-toggled": "#4b5563ff",
    "interactive-text-on-inverted": "#ffffffff",
    "elevation-surface-3": "#d1d5dbff",
    "elevation-outline-3": "#9ca3afff",
    "input-default-border": "#E0E0E0",
    "button-secondary-color": "#383838",
    "button-disabled-bg": "#383838",
    "button-disabled-text": "#ffffff",
    "button-tertiary-bg": "#FFD035",
    "button-tertiary-text": "#1C1C1C",
    "button-tertiary-bg-pressed": "#E8BB2A",
    "pill-default-border": "#bdbdbd",
    "pill-default-text": "#1c1c1c",
    "pill-filled-bg": "#FFD035",
    "pill-filled-border": "#FFD035",
    "pill-outlined-bg": "#E6F5EE",
    "pill-outlined-border": "#04954F",
    "pill-toggle-checked": "#393939",
    "interactive-active": "#FF6B00",
  },
  borderRadii: {
    none: 0,
    "2xs": 2,
    xs: 4,
    s: 6,
    sm: 8,
    ml: 12,
    xl: 16,
    "4xl": 24,
    full: 9999,
    "5xl": 28,
    "6xl": 32,
    m: 10,
    l: 14,
    "2xl": 18,
    "3xl": 20,
    "rounding-button-rounding": 30,
    "rounding-input-rounding": 6,
    "rounding-focus-rounding": 8,
  },
  spacing: {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "7": 28,
    "8": 32,
    "9": 36,
    "10": 40,
    "11": 44,
    "12": 48,
    "14": 56,
    "16": 64,
    "20": 80,
    "24": 96,
    "28": 112,
    "32": 128,
    "36": 144,
    "40": 160,
    "44": 176,
    "48": 192,
    "52": 208,
    "56": 224,
    "60": 240,
    "64": 256,
    "72": 288,
    "80": 320,
    "96": 384,
    px: 1,
    "0-5": 2,
    "1-5": 6,
    "2-5": 10,
    "3-5": 14,
    "height-height-s": 6,
    "height-height-m": 13,
    "height-height-l": 14,
    "height-height-xs": 2,
    "interior-icon-to-label-spacing": 4,
    "interior-input-side-spacing": 14,
    "hitbox-hitbox-xs": 10,
    "hitbox-hitbox-s": 6,
    "hitbox-hitbox-m": 2,
    "hitbox-hitbox-l": 0,
    "hitbox-hitbox-xxs": 12,
    "list-bottom": 128,
  },
  breakpoints: {
    smallPhone: 0,
    phone: 412,
    tablet: 768,
    tabletLandscape: 1024,
  },
  textVariants: {
    "variant-1": {
      fontSize: 14,
      fontFamily: "BalooBhai2-Regular",
      lineHeight: 20,
    },
    "variant-1-medium": {
      fontSize: 14,
      fontFamily: "BalooBhai2-Medium",
      lineHeight: 20,
    },
    "variant-1-bold": {
      fontSize: 14,
      fontFamily: "BalooBhai2-SemiBold",
      lineHeight: 20,
    },
    "variant-2": {
      fontSize: 16,
      fontFamily: "BalooBhai2-Regular",
      lineHeight: 22,
    },
    "variant-2-medium": {
      fontSize: 16,
      fontFamily: "BalooBhai2-Medium",
      lineHeight: 22,
    },
    "variant-2-bold": {
      fontSize: 16,
      fontFamily: "BalooBhai2-SemiBold",
      lineHeight: 22,
    },
    "variant-3": {
      fontSize: 18,
      fontFamily: "BalooBhai2-Regular",
      lineHeight: 26,
    },
    "variant-3-medium": {
      fontSize: 18,
      fontFamily: "BalooBhai2-Medium",
      lineHeight: 26,
    },
    "variant-3-bold": {
      fontSize: 18,
      fontFamily: "BalooBhai2-SemiBold",
      lineHeight: 26,
    },
    "variant-4": {
      fontSize: 22,
      fontFamily: "BalooBhai2-Regular",
      lineHeight: 32,
    },
    "variant-4-medium": {
      fontSize: 22,
      fontFamily: "BalooBhai2-Medium",
      lineHeight: 32,
    },
    "variant-4-bold": {
      fontSize: 22,
      fontFamily: "BalooBhai2-SemiBold",
      lineHeight: 32,
    },
    "variant-5": {
      fontSize: 26,
      fontFamily: "BalooBhai2-Regular",
      lineHeight: 36,
    },
    "variant-5-medium": {
      fontSize: 26,
      fontFamily: "BalooBhai2-Medium",
      lineHeight: 36,
    },
    "variant-5-bold": {
      fontSize: 26,
      fontFamily: "BalooBhai2-SemiBold",
      lineHeight: 36,
    },
    "variant-input": {
      fontSize: 16,
      fontFamily: "BalooBhai2-Regular",
      lineHeight: 26,
    },
    "variant-pill-toggle": {
      fontSize: 18,
      fontFamily: "BalooBhai2-Medium",
      lineHeight: 28,
    },
    defaults: {
      fontSize: 16,
      fontFamily: "BalooBhai2-Regular",
      lineHeight: 20,
    },
  },
  buttonVariants: {
    primary: {
      color: "interactive-primary-text-idle",
      colorPressed: "interactive-primary-text-pressed",
      colorDisabled: "button-disabled-text",
      backgroundColor: "interactive-primary-bg-idle",
      backgroundColorPressed: "interactive-primary-bg-pressed",
      backgroundColorDisabled: "button-disabled-bg",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
    },
    secondary: {
      color: "interactive-secondary-on-idle",
      colorPressed: "interactive-secondary-on-pressed",
      colorDisabled: "button-disabled-text",
      backgroundColor: "button-secondary-color",
      backgroundColorPressed: "interactive-secondary-on-pressed",
      backgroundColorDisabled: "button-disabled-bg",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
    },
    outlined: {
      color: "interactive-outlined-idle",
      colorPressed: "interactive-outlined-pressed",
      colorDisabled: "interactive-outlined-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "interactive-outlined-idle",
      borderColorPressed: "interactive-outlined-pressed",
      borderColorDisabled: "interactive-outlined-disabled",
    },
    text: {
      color: "interactive-primary-text-idle",
      colorPressed: "interactive-primary-text-pressed",
      colorDisabled: "button-disabled-text",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
    },
  },
  buttonWidths: {
    s: 142,
    m: 182,
    l: 234,
    fit: "100%",
  },
  buttonSizes: {
    small: "height-height-s",
    default: "height-height-m",
    large: "height-height-l",
  },
  pillSizes: {
    s: { vertical: 4, horizontal: 6 },
    m: { vertical: 8, horizontal: 10 },
    l: { vertical: 10, horizontal: 12 },
  },
  iconButtonVariants: {
    primary: {
      color: "interactive-primary-on",
      colorPressed: "interactive-primary-on",
      colorDisabled: "interactive-primary-on",
      backgroundColor: "elevation-background-dark-1",
      backgroundColorPressed: "informational-warning",
      backgroundColorDisabled: "informational-warning",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
    },
    transparent: {
      color: "interactive-primary-text-idle",
      colorPressed: "interactive-primary-text-pressed",
      colorDisabled: "informational-error",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
      borderColorDisabledToggled: "transparent",
    },
  },
  iconButtonSizes: {
    xs: "0",
    s: "height-height-s",
    m: "height-height-m",
    l: "height-height-l",
  },
  inputVariants: {
    outlined: {
      backgroundColor: "elevation-background-dark-1",
      backgroundColorActive: "elevation-background-dark-1",
      backgroundColorError: "elevation-background-dark-1",
      backgroundColorDisabled: "elevation-background-dark-1",
      borderColor: "interactive-border-1",
      borderColorActive: "interactive-border-1",
      borderColorError: "informational-error-outline",
      borderColorDisabled: "elevation-outline-2",
      color: "interactive-text-dark-1",
      colorActive: "interactive-text-dark-1",
      colorError: "interactive-text-dark-1",
      colorDisabled: "interactive-text-disabled",
      labelColor: "text-default-primary",
      labelColorActive: "text-default-primary",
      labelColorError: "text-default-primary",
      labelColorDisabled: "interactive-text-disabled",
    },
    filled: {
      backgroundColor: "interactive-text-dark-1",
      backgroundColorActive: "interactive-text-dark-1",
      backgroundColorError: "interactive-text-dark-1",
      backgroundColorDisabled: "interactive-text-dark-1",
      borderColor: "transparent",
      borderColorActive: "interactive-border-1",
      borderColorError: "informational-error-outline",
      borderColorDisabled: "transparent",
      color: "text-default-primary",
      colorActive: "text-default-primary",
      colorError: "text-default-primary",
      colorDisabled: "interactive-text-disabled",
      labelColor: "interactive-primary-text-idle",
      labelColorActive: "interactive-primary-text-idle",
      labelColorError: "interactive-primary-text-idle",
      labelColorDisabled: "interactive-primary-text-idle",
    },
  },
  pillVariants: {
    toggle: {
      color: "interactive-primary-text-idle",
      colorPressed: "interactive-tertiary-on",
      colorDisabled: "interactive-tertiary-on-disabled",
      backgroundColor: "interactive-primary-on",
      backgroundColorPressed: "interactive-primary-on",
      backgroundColorDisabled: "interactive-tertiary-idle",
      borderColor: "transparent",
      borderColorPressed: "interactive-tertiary-toggled",
      borderColorDisabled: "transparent",
      borderColorDisabledToggled: "interactive-tertiary-on-disabled",
      backgroundColorToggled: "pill-toggle-checked",
      colorToggled: "interactive-primary-on",
      boxShadow: "shadow-pill",
    },
    filled: {
      color: "interactive-primary-text-idle",
      colorPressed: "pill-default-text",
      colorDisabled: "pill-default-text",
      backgroundColor: "interactive-primary-bg-idle",
      backgroundColorPressed: "interactive-primary-bg-idle",
      backgroundColorDisabled: "interactive-primary-bg-idle",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
      borderColorDisabledToggled: "transparent",
      backgroundColorToggled: "pill-filled-bg",
      borderColorToggled: "transparent",
    },
    outlined: {
      color: "pill-default-text",
      colorPressed: "pill-default-text",
      colorDisabled: "pill-default-text",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "pill-default-border",
      borderColorPressed: "pill-outlined-border",
      borderColorDisabled: "pill-default-border",
      borderColorDisabledToggled: "pill-default-border",
      backgroundColorToggled: "pill-outlined-bg",
      borderColorToggled: "pill-outlined-border",
    },
  },
  textButtonVariants: {
    secondary: {
      color: "interactive-primary-text-idle",
      colorPressed: "interactive-primary-text-pressed",
      colorDisabled: "interactive-text-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      iconColor: "interactive-primary-bg-idle",
      iconColorPressed: "interactive-primary-bg-pressed",
      iconColorDisabled: "interactive-primary-text-disabled",
    },
    primary: {
      color: "interactive-primary-bg-idle",
      colorPressed: "interactive-primary-bg-pressed",
      colorDisabled: "interactive-text-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      iconColor: "interactive-primary-bg-idle",
      iconColorPressed: "interactive-primary-bg-pressed",
      iconColorDisabled: "interactive-primary-text-disabled",
    },
    toast: {
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      color: "interactive-text-on-inverted",
      colorPressed: "interactive-text-pressed",
      colorDisabled: "interactive-text-disabled",
      iconColor: "interactive-text-on-inverted",
      iconColorPressed: "interactive-text-pressed",
      iconColorDisabled: "interactive-text-disabled",
    },
  },
  toastVariants: {
    neutral: {
      backgroundColor: "interactive-secondary-idle",
    },
    success: {
      backgroundColor: "informational-success",
    },
    warning: {
      backgroundColor: "informational-warning",
    },
    error: {
      backgroundColor: "informational-error",
    },
  },
  listItems: {
    single: {
      backgroundColor: "transparent",
      backgroundColorSelected: "elevation-background-dark-1",
      backgroundColorPressed: "transparent",
      labelColor: "interactive-text-dark-1",
      labelColorSelected: "interactive-text-dark-1",
      labelColorPressed: "interactive-text-dark-1",
      sublabelColor: "text-default-tertiary",
      sublabelColorSelected: "text-inverted-tertiary",
      borderColor: "elevation-outline-1",
      borderRadius: "none",
    },
    multiple: {
      backgroundColor: "transparent",
      backgroundColorSelected: "transparent",
      backgroundColorPressed: "transparent",
      labelColor: "interactive-text-on-bg",
      labelColorSelected: "interactive-text-on-bg",
      labelColorPressed: "interactive-text-pressed",
      sublabelColor: "text-default-tertiary",
      sublabelColorSelected: "text-default-tertiary",
      borderColor: "elevation-outline-1",
      borderRadius: "none",
    },
    action: {
      backgroundColor: "elevation-background",
      backgroundColorSelected: "elevation-background",
      backgroundColorPressed: "elevation-background",
      labelColor: "interactive-text-on-bg",
      labelColorSelected: "interactive-text-on-inverted",
      labelColorPressed: "interactive-text-pressed",
      sublabelColor: "text-default-tertiary",
      sublabelColorSelected: "text-inverted-tertiary",
      borderColor: "transparent",
      borderRadius: "4xl",
    },
  },
  shadows: {
    "shadow-1": {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1,
      elevation: 3,
    },
    "shadow-2": {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 2.22,
      elevation: 5,
    },
    "shadow-3": {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.15,
      shadowRadius: 2.62,
      elevation: 8,
    },
    "shadow-4": {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 12,
      },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 16,
    },
    "shadow-pill": {
      shadowColor: "#000000",
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 4,
    },
  },
  blurs: {
    "bg-blur-0": 0,
    "bg-blur-1": 10,
    "bg-blur-2": 20,
    "bg-blur-3": 30,
    "bg-blur-4": 50,
    "bg-blur-5": 60,
    "bg-blur-6": 70,
    "bg-blur-7": 80,
  },
} as const);

export type Theme = typeof theme;
export type ThemeColor = keyof Theme["colors"];

export default theme;
